# Generated by Django 5.1.2 on 2024-11-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('title', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('published', models.BooleanField(default=False)),
                ('date', models.DateField(blank=True)),
                ('content', models.TextField()),
            ],
        ),
    ]
